# What is Pandas

--it is a python library used for working with data sets.

--it has a functions for analyzing,cleaning,exploring and manipulating data.

--Pandas means 'Panel Data System' and 'Python Data Analysis' , it was created by wes Mckinney in 2008.

# Two types in pandas.

1)Series - it is a one dimensional array holding data of any type.it is like a column in data.

2)DataFrame - it is used for 2-d or more dimensional array table generation

In [2]:
import numpy as np
import pandas as pd

#syntax for series

pd.Series (data,index)

In [3]:
ar=np.array([12,90,54,56])
print(ar)
print(type(ar))

[12 90 54 56]
<class 'numpy.ndarray'>


In [7]:
ser=pd.Series(ar)
ser

0    12
1    90
2    54
3    56
dtype: int32

In [8]:
ser=pd.Series(data=ar,index=['A','B','C','D'])
ser

A    12
B    90
C    54
D    56
dtype: int32

In [9]:
#TO access the series table values
print(ser[0])

12


In [10]:
print(ser['B'])

90


In [11]:
ser[0]=45
print(ser)

A    45
B    90
C    54
D    56
dtype: int32


In [13]:
ar1=np.arange(8,dtype=float)
print(ar1)
print('-'*40)
ser1=pd.Series(ar1)
ser1

[0. 1. 2. 3. 4. 5. 6. 7.]
----------------------------------------


0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
dtype: float64

In [14]:
ar2=np.array(['Abu','raju','arjun','david','gill'])
print(ar2)
print(ar2.dtype)

['Abu' 'raju' 'arjun' 'david' 'gill']
<U5


In [15]:
ser2=pd.Series(ar2)
ser2

0      Abu
1     raju
2    arjun
3    david
4     gill
dtype: object

In [20]:
#To create a series using Dictionary.
data={'Abu':'data analyst','raju':'developer','askar':'room cleaner'}
rs=pd.Series(data)
rs

Abu      data analyst
raju        developer
askar    room cleaner
dtype: object

In [21]:
se=pd.Series(data,name='Database')
se

Abu      data analyst
raju        developer
askar    room cleaner
Name: Database, dtype: object

In [22]:
ran=np.random.randint(0,15,5)
ser=pd.Series(ran)
ser

0    13
1    11
2     6
3     2
4    13
dtype: int32

In [23]:
ran=np.random.randint(0,20,7)
ser=pd.Series(ran)
ser

0    19
1     4
2    15
3     9
4     8
5    14
6    11
dtype: int32

In [24]:
#Creating a series from scalar values.

ser3=pd.Series(data=5,index=['A','B','C','D'])
ser3

A    5
B    5
C    5
D    5
dtype: int64

In [25]:
dic={'A':3.00,'B':2.50,'C':3.25,'D':3.80}
ser3=pd.Series(dic)
ser

0    19
1     4
2    15
3     9
4     8
5    14
6    11
dtype: int32

In [27]:
ser3['A']

3.0

In [29]:
ser3[['A','B']]

A    3.0
B    2.5
dtype: float64

In [30]:
ser>3

0    True
1    True
2    True
3    True
4    True
5    True
6    True
dtype: bool

In [31]:
ser[ser>3]

0    19
1     4
2    15
3     9
4     8
5    14
6    11
dtype: int32

In [33]:
'B'in ser3

True

In [34]:
ser3.values

array([3.  , 2.5 , 3.25, 3.8 ])

In [35]:
ser3.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [36]:
#Arithmetic Operation.
ser1=pd.Series([2.0,3.0,2.5,2.0])
ser1

0    2.0
1    3.0
2    2.5
3    2.0
dtype: float64

In [37]:
ser2=pd.Series([2.0,3.0,2.5,2.0],index=['A','B','C','D'])
ser2

A    2.0
B    3.0
C    2.5
D    2.0
dtype: float64

In [38]:
ser1+ser2

0   NaN
1   NaN
2   NaN
3   NaN
A   NaN
B   NaN
C   NaN
D   NaN
dtype: float64

In [39]:
ser3+ser2

A    5.00
B    5.50
C    5.75
D    5.80
dtype: float64

In [40]:
ar=pd.Series([np.nan,10,54,np.nan,35])
print(ar)

0     NaN
1    10.0
2    54.0
3     NaN
4    35.0
dtype: float64


In [3]:
import numpy as np
import pandas as pd
ser=pd.Series(np.arange(2,8))
ser



0    2
1    3
2    4
3    5
4    6
5    7
dtype: int32

In [5]:
ser.replace(2,'$')

0    $
1    3
2    4
3    5
4    6
5    7
dtype: object

In [7]:
ser

0    2
1    3
2    4
3    5
4    6
5    7
dtype: int32

In [17]:
ser.replace(5,'&',inplace=True)
ser

0    2
1    3
2    4
3    &
4    6
5    7
dtype: object

In [10]:
ser.replace(7,'#',inplace=False)
ser

0    2
1    3
2    4
3    &
4    6
5    7
dtype: object

In [14]:
ser

0    2
1    3
2    4
3    &
4    6
5    7
dtype: object

In [18]:
ser.replace(['&',6],[11,12],inplace=True)
ser

0     2
1     3
2     4
3    11
4    12
5     7
dtype: int64

In [19]:
ser.replace({3:90},inplace=True)
ser

0     2
1    90
2     4
3    11
4    12
5     7
dtype: int64

In [20]:
ser.replace(4,method='bfill') #bfill - fill the values in backwards.


0     2
1    90
2    11
3    11
4    12
5     7
dtype: int64

In [24]:
ser.replace(11,method='ffill') #ffill -- fill the value in forwards.


0     2
1    90
2     4
3     4
4    12
5     7
dtype: int64

# Data Frames:

Data frames are actually multiple series sharing the same index. DataFrames are very important when it comes tp large datasets.


it can generate table for one or more dimensional array.

In [25]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame


In [26]:
li=[[3,4,5,6],[9,8,10,12]]
print(li)
print(type(li))

[[3, 4, 5, 6], [9, 8, 10, 12]]
<class 'list'>


In [28]:
#To change list into data frame

df=DataFrame(data=li)
df

0  1   2   3
0  3  4   5   6
1  9  8  10  12

In [29]:
df[1]

0    4
1    8
Name: 1, dtype: int64

In [30]:
#To change the list into dataframe.
df=DataFrame(data=li,index=['row1','row2'],columns=['col1','col2','col3','col4'])
df

col1  col2  col3  col4
row1     3     4     5     6
row2     9     8    10    12

In [31]:
#To change the array value into dataframe.
ar=np.arange(8)
ar

array([0, 1, 2, 3, 4, 5, 6, 7])

In [32]:
ar1=ar.reshape(2,4)
ar1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [33]:
df1=DataFrame(ar1,['R1','R2'],['C1','C2','C3','C4'])
df1

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7

In [34]:
#To select the list of columns
df1[['C2','C3']]

C2  C3
R1   1   2
R2   5   6

# Selecting the rows
1)loc  - Enter Index Label

2)iloc - Enter the Index Number

In [35]:
df1

C1  C2  C3  C4
R1   0   1   2   3
R2   4   5   6   7

In [36]:
df1.loc['R1']

C1    0
C2    1
C3    2
C4    3
Name: R1, dtype: int32

In [38]:
df1.iloc[1]

C1    4
C2    5
C3    6
C4    7
Name: R2, dtype: int32

In [39]:
#Conditional Selection (masking)
df1>5

C1     C2     C3     C4
R1  False  False  False  False
R2  False  False   True   True

In [40]:
df1[df1>5]

C1  C2   C3   C4
R1 NaN NaN  NaN  NaN
R2 NaN NaN  6.0  7.0

In [41]:
df1[(df1['C1']>3) | (df1['C1']==1)]

C1  C2  C3  C4
R2   4   5   6   7

In [42]:
#To convert disctionary into dataframe.
df2=DataFrame({
    'Name':['suba','maha','david','raju','abu'],
    'Degree':['B.com','MBA','MSC','B.E','M.E'],
    'Salary':[10000,20000,30000,40000,50000]})
df2

Name Degree  Salary
0   suba  B.com   10000
1   maha    MBA   20000
2  david    MSC   30000
3   raju    B.E   40000
4    abu    M.E   50000

In [43]:
df2.replace(30000,60000,inplace=True)

In [44]:
df2

Name Degree  Salary
0   suba  B.com   10000
1   maha    MBA   20000
2  david    MSC   60000
3   raju    B.E   40000
4    abu    M.E   50000

In [45]:
df2.replace({'Name':{'suba':'kareem','maha':'bheem'}},inplace=True)

In [46]:
df2

Name Degree  Salary
0  kareem  B.com   10000
1   bheem    MBA   20000
2   david    MSC   60000
3    raju    B.E   40000
4     abu    M.E   50000

In [47]:
df2.columns

Index(['Name', 'Degree', 'Salary'], dtype='object')

In [48]:
df2.index

RangeIndex(start=0, stop=5, step=1)

In [52]:
df2.sort_values(by='Name')


Name Degree  Salary
4     abu    M.E   50000
1   bheem    MBA   20000
2   david    MSC   60000
0  kareem  B.com   10000
3    raju    B.E   40000

# Column or Row Elimination

Drop - function used to eliminate columns or rows in the DataFrame.

In [6]:
#series
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
ser=Series(np.arange(1,5),index=['row1','row2','row3','row4'])
ser

row1    1
row2    2
row3    3
row4    4
dtype: int32

In [7]:
ser.drop('row1')

row2    2
row3    3
row4    4
dtype: int32

In [8]:
ser

row1    1
row2    2
row3    3
row4    4
dtype: int32

In [9]:
ser.drop('row1',inplace=True)

In [10]:
ser

row2    2
row3    3
row4    4
dtype: int32

In [16]:
ser.drop((['row3','row2']),inplace=True)

In [17]:
ser

row4    4
dtype: int32

In [20]:
#how to eliminate the dataframe row and columns
df1=DataFrame(np.arange(25).reshape(5,5),
             index=['row1','row2','row3','row4','row5'],
             columns=['col1','col2','col3','col4','col5'])
df1                    

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19
row5    20    21    22    23    24

In [22]:
df1.drop('col1',axis=1)

col2  col3  col4  col5
row1     1     2     3     4
row2     6     7     8     9
row3    11    12    13    14
row4    16    17    18    19
row5    21    22    23    24

In [23]:
df1.drop('row1')

col1  col2  col3  col4  col5
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19
row5    20    21    22    23    24

In [24]:
df1.drop(columns='col1',inplace=True)

In [25]:
df1

col2  col3  col4  col5
row1     1     2     3     4
row2     6     7     8     9
row3    11    12    13    14
row4    16    17    18    19
row5    21    22    23    24

In [26]:
df1.drop(columns='col2',index='row1',inplace=True)
df1

col3  col4  col5
row2     7     8     9
row3    12    13    14
row4    17    18    19
row5    22    23    24

In [27]:
#missing series
s=Series([np.nan,2,3,4,np.nan],
        index=['R1','R2','R3','R4','R5'])
s

R1    NaN
R2    2.0
R3    3.0
R4    4.0
R5    NaN
dtype: float64

In [28]:
s.isnull()

R1     True
R2    False
R3    False
R4    False
R5     True
dtype: bool

In [29]:
#dropna - drops the rows with missing values
s.dropna

<bound method Series.dropna of R1    NaN
R2    2.0
R3    3.0
R4    4.0
R5    NaN
dtype: float64>

In [30]:
s.dropna()

R2    2.0
R3    3.0
R4    4.0
dtype: float64